name = "SteamPunkThree"
author = "Arceus3251"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "90cf3b2ccc33ce0200779a38f1a4b525ae5370e4ef159c0c5900e66599181044"

[versions]
forge = "43.3.5"
minecraft = "1.19.2"
