name = "SteamPunkThree"
author = "Arceus3251"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b7a3f05022d6c4e72e401c91206d47c5b9646e39c07232937cdc3cbace100002"

[versions]
forge = "43.3.5"
minecraft = "1.19.2"
