name = "SteamPunkThree"
author = "Arceus3251"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "02cac9a1e5f3abb1052c7d0731e4c41923a5ccb5ae4b3f2cc697629dc3779321"

[versions]
forge = "43.3.5"
minecraft = "1.19.2"
