name = "SteamPunkThree"
author = "Arceus3251"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a362b52bbe9424bd6ae40ca46452bfdbeb898320e12ea6b6ed49dd34884f07d3"

[versions]
forge = "43.3.5"
minecraft = "1.19.2"
