name = "Smoop 2"
author = "SmoopModTeam"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "02b416cae7ad668eb24e67da66c031e7097eab9a9f8d8c610b77c1c77646a819"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
