name = "Smoop 2"
author = "SmoopModTeam"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eedc2da2413e288b32720534e9872ce4124d2b744f4c5aa9cc4a593459e29809"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
