name = "Smoop 2"
author = "SmoopModTeam"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "22c826c0b3a8dd4570b014f7644eab3b32f898563cc83473d528f294feda8a7d"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
