name = "Smoop 2"
author = "SmoopModTeam"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8466c461ccb4446b92ec4d16f2a350fb58e846c651466791dad76968ff5d6798"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
