name = "Smoop 2"
author = "SmoopModTeam"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f9090caad13d5a9f1852bdf1c63adefff0b6559cd8011a5f2e12373590394e92"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
