name = "Smoop 2"
author = "SmoopModTeam"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1451c7f0c5f9522a6f340e69467b29c59e3edbde304f93c1d6830e39e81bceb0"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
