name = "Smoop 2"
author = "SmoopModTeam"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "783dcb084f96692ea3c7a3b954b430e8299be29118b56ef87533bf0da69c8313"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
