name = "Smoop 2"
author = "SmoopModTeam"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ad58eb8b733b830fac17b4d4e4590af1c5dbd82d6349194091dfd2b7c17bdf1f"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
