name = "Smoop 2"
author = "SmoopModTeam"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1e292992b26aada2d6c71593cae36deb2b76824a8372c656e73ee56beb9c613c"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
