name = "Smoop 2"
author = "SmoopModTeam"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "817206f5023a11d971896bb730e7dd5c903006e15550f4fd567451b6afea97c0"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
