name = "Smoop 2"
author = "SmoopModTeam"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2facbdf3bab4df2e48ea232db1e26777b47016d3ce451b28484a135d1632368a"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
