name = "Smoop 2"
author = "SmoopModTeam"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ec037c3e4144ea34daa880d6f2a618c9d209270db00be3cc71d7ae619572dc97"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
