name = "Smoop 2"
author = "SmoopModTeam"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d3ecc4c5bc37a9ca996f21583ccb2c4df1dd3d1e698d832e2e098597901eeb34"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"

[options]
datapack-folder = "datapacks/"
