name = "Smoop 2"
author = "SmoopModTeam"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb423a1914b784f7b5015b26f1d43fb0e7f82f9b7aa6ec2bb506354c0d5f2dd5"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
