name = "Smoop 2"
author = "SmoopModTeam"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4374b4903eb451ed5c589257dda7be4ca5df0147406b07459e21ee7799d86832"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
