name = "Smoop 2 Beta"
author = "SmoopModTeam"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "30a14381cb916c6a9808a10aa9df06f4086f298f4cbb12c725e5e94851a32990"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"

[options]
datapack-folder = "datapacks/"
